site_name: Documentation
pages:
- Getting Started:
    - What is Structure: getting-started/what-is-structure.md
    - Structure Walkthrough: getting-started/walkthrough.md
    - Boards:
        - Getting Started with the Intel Edison: mqtt.md
        - Getting Started with the Raspberry PI: mqtt.md
        - Getting Started with the Arduino 101: getting-started/boards/getting-started-with-arduino-wifi-101.md
        - Getting Started with the AdaFruit Feather Huzzah: mqtt.md
- Security:
    - Overview: security.md
    - Access Keys: mqtt.md
- Applications:
    - Overview: mqtt.md
    - Access Keys: mqtt.md
    - Webhooks: mqtt.md
- Devices:
    - Device Overview: devices/overview.md
    - Device State: devices/state.md
    - Device Commands: devices/commands.md
    - Device Queries: devices/device-queries.md
- Dashboards:
    - Overview: dashboards/overview.md
    - Time Series Graph: dashboards/time-series-graph.md
    - GPS Heatmap: dashboards/gps-heatmap.md
    - GPS History: dashboards/gps-history.md
    - Gauge: dashboards/gauge.md
    - Pie Chart: dashboards/pie-chart.md
    - Data Table: dashboards/data-table.md
    - Device Connection Log: dashboards/device-connection-log.md
    - Event List: mqtt.md
    - External Website: dashboards/external-website.md
    - Device List: dashboards/device-list.md
    - Workflow List: dashboards/workflow-list.md
    - Application List: dashboards/application-list.md
- Workflows:
    - Overview: workflows/overview.md
    - Triggers:
        - Overview: mqtt.md
        - Device: workflows/triggers/device.md
        - Event: workflows/triggers/event.md
        - MQTT: workflows/triggers/mqtt.md
        - Timer: workflows/triggers/timer.md
        - Virtual Button: workflows/triggers/virtual-button.md
        - Webhook: workflows/triggers/webhook.md
    - Logic:
        - Conditional: workflows/logic/conditional.md
        - Delay: workflows/logic/delay.md
        - Function: workflows/logic/function.md
        - Geofence: workflows/logic/geofence.md
        - JSON Encode: workflows/logic/json-encode.md
        - JSON Decode: workflows/logic/json-decode.md
        - Math: workflows/logic/math.md
        - Mutate: workflows/logic/mutate.md
        - On Change: workflows/logic/on-change.md
        - Throttle: workflows/logic/throttle.md
        - Validate Payload: workflows/logic/validate-payload.md
- MQTT: mqtt.md
theme_dir: 'structure'
extra:
    site_title: 'Structure Documentation'
