site_name: Documentation
site_url: https://docs.losant.com
pages:
- Getting Started:
    - What is Losant: getting-started/what-is-losant.md
    - Losant Walkthrough: getting-started/walkthrough.md
    - Losant IoT Dev Kits:
        - Overview: getting-started/losant-iot-dev-kits/overview.md
        - Environment Setup: getting-started/losant-iot-dev-kits/environment-setup.md
        - Builder Kit Instructions: getting-started/losant-iot-dev-kits/builder-kit.md
        - Builder Kit Nodevember Instructions: getting-started/losant-iot-dev-kits/builder-kit-nodevember.md
        - Builder Kit Feather Instructions: getting-started/losant-iot-dev-kits/builder-kit-feather.md
        - Builder Kit Particle Instructions: getting-started/losant-iot-dev-kits/builder-kit-particle.md
        - Builder Kit Salesforce Instructions: getting-started/losant-iot-dev-kits/builder-kit-salesforce.md
        - Moisture Sensor Kit Instructions: getting-started/losant-iot-dev-kits/moisture-sensor-kit.md
        - Door Sensor Kit Instructions: getting-started/losant-iot-dev-kits/door-sensor-kit.md
        - LCD Kit Instructions: getting-started/losant-iot-dev-kits/lcd-kit.md
    - Boards:
        - Getting Started with Intel Edison: getting-started/boards/getting-started-with-intel-edison.md
        - Getting Started with Raspberry PI: getting-started/boards/getting-started-with-raspberry-pi.md
        - Getting Started with Arduino: getting-started/boards/getting-started-with-arduino-wifi-101.md
    - Tutorials And Projects: getting-started/tutorials.md
- Security:
    - Overview: security.md
- User Accounts:
    - Overview: user-accounts/overview.md
    - Sandbox: user-accounts/sandbox.md
- Organizations:
    - Overview: organizations/overview.md
    - Members: organizations/members.md
    - Resource Limits: organizations/resource-limits.md
    - Transferring Resources: organizations/transferring-resources.md
    - Audit Logs: organizations/audit-logs.md
- Applications:
    - Overview: applications/overview.md
    - Access Keys: applications/access-keys.md
    - Application Tokens: applications/application-tokens.md
    - Data Explorer: applications/data-explorer.md
    - Events: applications/events.md
    - Integrations: applications/integrations.md
    - Webhooks: applications/webhooks.md
- Experiences:
    - Overview: experiences/overview.md
    - Endpoints: experiences/endpoints.md
    - Groups: experiences/groups.md
    - Users: experiences/users.md
    - Walkthrough:
        - Overview: experiences/walkthrough/overview.md
        - Part 1 - User Registration: experiences/walkthrough/part1.md
        - Part 2 - User Authentication: experiences/walkthrough/part2.md
        - Part 3 - Device Registration: experiences/walkthrough/part3.md
        - Part 4 - Viewing Device Data: experiences/walkthrough/part4.md
- Devices:
    - Device Overview: devices/overview.md
    - Device State: devices/state.md
    - Device Commands: devices/commands.md
    - Device Queries: devices/device-queries.md
    - Gateways and Peripherals : devices/gateways-peripherals.md
    - Device Recipes: devices/device-recipes.md
- Dashboards:
    - Overview: dashboards/overview.md
    - Context Variables: dashboards/context-variables.md
    - Application List: dashboards/application-list.md
    - Bar Chart: dashboards/bar-chart.md
    - Dashboard List: dashboards/dashboard-list.md
    - Data Table: dashboards/data-table.md
    - Device Connection Log: dashboards/device-connection-log.md
    - Device List: dashboards/device-list.md
    - Event List: dashboards/event-list.md
    - External Website: dashboards/external-website.md
    - Gauge: dashboards/gauge.md
    - GPS Heatmap: dashboards/gps-heatmap.md
    - GPS History: dashboards/gps-history.md
    - Indicator: dashboards/indicator.md
    - Input Controls: dashboards/input-controls.md
    - Open Event Indicator: dashboards/open-event-indicator.md
    - Pie Chart: dashboards/pie-chart.md
    - Section Header: dashboards/section-header.md
    - Time Series Graph: dashboards/time-series-graph.md
    - Workflow List: dashboards/workflow-list.md
- Workflows:
    - Overview: workflows/overview.md
    - Accessing Payload Data: workflows/accessing-payload-data.md
    - Versioning: workflows/versioning.md
    - Triggers:
        - Device: workflows/triggers/device.md
        - On Connect: workflows/triggers/on-connect.md
        - On Disconnect: workflows/triggers/on-disconnect.md
        - Endpoint: workflows/triggers/endpoint.md
        - Event: workflows/triggers/event.md
        - Google Pub/Sub: workflows/triggers/google-pub-sub.md
        - MQTT: workflows/triggers/mqtt.md
        - Particle: workflows/triggers/particle.md
        - Timer: workflows/triggers/timer.md
        - Virtual Button: workflows/triggers/virtual-button.md
        - Webhook: workflows/triggers/webhook.md
    - Experience:
        - Authenticate: workflows/experience/authenticate.md
        - Create User: workflows/experience/create-user.md
        - Delete User: workflows/experience/delete-user.md
        - Generate Token: workflows/experience/generate-token.md
        - Get User: workflows/experience/get-user.md
        - Update User: workflows/experience/update-user.md
    - Logic:
        - Array: workflows/logic/array.md
        - Conditional: workflows/logic/conditional.md
        - Delay: workflows/logic/delay.md
        - Function: workflows/logic/function.md
        - Geofence: workflows/logic/geofence.md
        - HTML/XML Parser: workflows/logic/html-parser.md
        - JSON Decode: workflows/logic/json-decode.md
        - JSON Encode: workflows/logic/json-encode.md
        - Latch: workflows/logic/latch.md
        - Loop: workflows/logic/loop.md
        - Math: workflows/logic/math.md
        - Mutate: workflows/logic/mutate.md
        - On Change: workflows/logic/on-change.md
        - Random Number: workflows/logic/random-number.md
        - Switch: workflows/logic/switch.md
        - Throttle: workflows/logic/throttle.md
        - Time Range: workflows/logic/time-range.md
        - Validate Payload: workflows/logic/validate-payload.md
    - Data:
        - AWS Lambda: workflows/data/aws-lambda.md
        - Create Device: workflows/data/create-device.md
        - Gauge Query: workflows/data/gauge-query.md
        - Get Device: workflows/data/get-device.md
        - Get Value: workflows/data/get-value.md
        - HTTP: workflows/data/http.md
        - Losant API: workflows/data/losant-api.md
        - MongoDB: workflows/data/mongo.md
        - Redis: workflows/data/redis.md
        - Salesforce Cases: workflows/data/salesforce-cases.md
        - Store Value: workflows/data/store-value.md
        - Time Series: workflows/data/time-series.md
        - Update Device: workflows/data/update-device.md
    - Outputs:
        - Debug: workflows/outputs/debug.md
        - Device Command: workflows/outputs/device-command.md
        - Device State: workflows/outputs/device-state.md
        - Email: workflows/outputs/email.md
        - Endpoint Reply: workflows/outputs/endpoint-reply.md
        - Google Pub/Sub: workflows/outputs/google-pub-sub.md
        - HTTP: workflows/outputs/http.md
        - Modify Event: workflows/outputs/modify-event.md
        - MQTT: workflows/outputs/mqtt.md
        - Particle Call: workflows/outputs/particle-call.md
        - Record Event: workflows/outputs/record-event.md
        - SendGrid: workflows/outputs/sendgrid.md
        - Slack: workflows/outputs/slack.md
        - SMS: workflows/outputs/sms.md
        - Tweet: workflows/outputs/tweet.md
        - Twilio: workflows/outputs/twilio.md
        - Webhook Reply: workflows/outputs/webhook-reply.md
        - Workflow Trigger: workflows/outputs/workflow-trigger.md
- Losant Go:
    - Overview: losant-go/overview.md
- MQTT:
    - Overview: mqtt/overview.md
    - Arduino: mqtt/arduino.md
    - JavaScript: mqtt/javascript.md
    - Python: mqtt/python.md
    - Ruby: mqtt/ruby.md
- REST API:
    - Overview: rest-api/overview.md
    - Application API Token: rest-api/application-api-token.md
    - Application API Tokens: rest-api/application-api-tokens.md
    - Application Key: rest-api/application-key.md
    - Application Keys: rest-api/application-keys.md
    - Application: rest-api/application.md
    - Applications: rest-api/applications.md
    - Audit Log: rest-api/audit-log.md
    - Audit Logs: rest-api/audit-logs.md
    - Auth: rest-api/auth.md
    - Dashboard: rest-api/dashboard.md
    - Dashboards: rest-api/dashboards.md
    - Data: rest-api/data.md
    - Device Recipe: rest-api/device-recipe.md
    - Device Recipes: rest-api/device-recipes.md
    - Device: rest-api/device.md
    - Devices: rest-api/devices.md
    - Event: rest-api/event.md
    - Events: rest-api/events.md
    - Experience Endpoint: rest-api/experience-endpoint.md
    - Experience Endpoints: rest-api/experience-endpoints.md
    - Experience Group: rest-api/experience-group.md
    - Experience Groups: rest-api/experience-groups.md
    - Experience User: rest-api/experience-user.md
    - Experience Users: rest-api/experience-users.md
    - Integration: rest-api/integration.md
    - Integrations: rest-api/integrations.md
    - Me: rest-api/me.md
    - Organization: rest-api/org.md
    - Organizations: rest-api/orgs.md
    - Organization Invites: rest-api/org-invites.md
    - Webhook: rest-api/webhook.md
    - Webhooks: rest-api/webhooks.md
    - Workflow: rest-api/flow.md
    - Workflows: rest-api/flows.md
    - Workflow Version: rest-api/flow-version.md
    - Workflow Versions: rest-api/flow-versions.md
    - Schemas: rest-api/schemas.md
theme_dir: 'losant'
extra:
  site_title: 'Losant Documentation'
  hidden: ['Builder Kit Feather Instructions', 'Builder Kit Nodevember Instructions']
