site_name: Documentation
pages:
- Getting Started:
    - What is Structure: getting-started/what-is-structure.md
    - Structure Walkthrough: getting-started/walkthrough.md
    - Boards:
        - Getting Started with Intel Edison: getting-started/boards/getting-started-with-intel-edison.md
        - Getting Started with Arduino: getting-started/boards/getting-started-with-arduino-wifi-101.md
- Security:
    - Overview: security.md
- User Accounts:
    - Overview: user-accounts/overview.md
- Applications:
    - Overview: applications/overview.md
    - Access Keys: applications/access-keys.md
    - Webhooks: applications/webhooks.md
- Events:
    - Overview: events/overview.md
- Devices:
    - Device Overview: devices/overview.md
    - Device State: devices/state.md
    - Device Commands: devices/commands.md
    - Device Queries: devices/device-queries.md
- Dashboards:
    - Overview: dashboards/overview.md
    - Time Series Graph: dashboards/time-series-graph.md
    - GPS Heatmap: dashboards/gps-heatmap.md
    - GPS History: dashboards/gps-history.md
    - Gauge: dashboards/gauge.md
    - Pie Chart: dashboards/pie-chart.md
    - Data Table: dashboards/data-table.md
    - Device Connection Log: dashboards/device-connection-log.md
    - Event List: dashboards/event-list.md
    - External Website: dashboards/external-website.md
    - Device List: dashboards/device-list.md
    - Workflow List: dashboards/workflow-list.md
    - Application List: dashboards/application-list.md
- Workflows:
    - Overview: workflows/overview.md
    - Triggers:
        - Device: workflows/triggers/device.md
        - Event: workflows/triggers/event.md
        - MQTT: workflows/triggers/mqtt.md
        - Timer: workflows/triggers/timer.md
        - Virtual Button: workflows/triggers/virtual-button.md
        - Webhook: workflows/triggers/webhook.md
    - Logic:
        - Conditional: workflows/logic/conditional.md
        - Delay: workflows/logic/delay.md
        - Function: workflows/logic/function.md
        - Geofence: workflows/logic/geofence.md
        - JSON Encode: workflows/logic/json-encode.md
        - JSON Decode: workflows/logic/json-decode.md
        - Math: workflows/logic/math.md
        - Mutate: workflows/logic/mutate.md
        - On Change: workflows/logic/on-change.md
        - Throttle: workflows/logic/throttle.md
        - Validate Payload: workflows/logic/validate-payload.md
    - Data:
        - Get Value: workflows/data/get-value.md
        - HTTP: workflows/data/http.md
        - Store Value: workflows/data/store-value.md
    - Outputs:
        - Debug: workflows/outputs/debug.md
        - Device Command: workflows/outputs/device-command.md
        - Record Event: workflows/outputs/record-event.md
        - HTTP: workflows/outputs/http.md
        - MQTT: workflows/outputs/mqtt.md
        - SendGrid: workflows/outputs/sendgrid.md
        #- Slack: workflows/outputs/slack.md
        - Email: workflows/outputs/email.md
        - SMS: workflows/outputs/sms.md
        #- Tweet: workflows/outputs/tweet.md
        #- Twilio: workflows/outputs/twilio.md
        - Virtual Device: workflows/outputs/virtual-device.md
- Structure SDKs:
    - JavaScript: structure-sdks/javascript.md
    - Arduino: structure-sdks/arduino.md
- REST API:
    - Overview: rest-api/overview.md
- MQTT:
    - Overview: mqtt/overview.md
- Limits:
    - Overview: limits/overview.md
theme_dir: 'structure'
extra:
    site_title: 'Structure Documentation'
