site_name: Documentation
pages:
- Getting Started:
    - What is Structure: getting-started/what-is-structure.md
    - Getting Started with the Intel Edison: mqtt.md
    - Getting Started with the Raspberry PI: mqtt.md
    - Getting Started with the Arduino 101: getting-started/getting-started-with-arduino-wifi-101.md
    - Getting Started with the AdaFruit Feather Huzzah: mqtt.md
- Security:
    - Overview: security.md
    - Access Keys: mqtt.md
- Applications:
    - Overview: mqtt.md
    - Access Keys: mqtt.md
    - Webhooks: mqtt.md
- Devices:
    - Device Overview: devices/overview.md
    - Device State: devices/state.md
    - Device Commands: devices/commands.md
    - Device Queries: devices/device-queries.md
- Dashboards:
    - Overview: mqtt.md
    - Time Series Graph: dashboards/time-series-graph.md
    - GPS Heatmap: dashboards/gps-heatmap.md
    - GPS History: mqtt.md
    - Gauge: mqtt.md
    - Pie Chart: mqtt.md
    - Data Table: mqtt.md
    - Device Connection Log: mqtt.md
    - Event List: mqtt.md
    - External Website: mqtt.md
    - Device List: mqtt.md
    - Workflow List: mqtt.md
    - Application List: mqtt.md
- Workflows:
    - Overview: mqtt.md
    - Triggers:
        - Overview: mqtt.md
        - Device: workflows/triggers/device.md
        - Event: workflows/triggers/event.md
        - MQTT: workflows/triggers/mqtt.md
        - Timer: workflows/triggers/timer.md
        - Virtual Button: workflows/triggers/virtual-button.md
        - Webhook: workflows/triggers/webhook.md
    - Logic:
        - Conditional: workflows/logic/conditional.md
- MQTT: mqtt.md
theme_dir: 'structure'
extra:
    site_title: 'Structure Documentation'
