site_name: Documentation
pages:
- Getting Started:
    - What is Losant: getting-started/what-is-losant.md
    - Losant Walkthrough: getting-started/walkthrough.md
    - Losant IoT Dev Kits:
        - Overview: getting-started/losant-iot-dev-kits/overview.md
        - Environment Setup: getting-started/losant-iot-dev-kits/environment-setup.md
        - Builder Kit Instructions: getting-started/losant-iot-dev-kits/builder-kit.md
        - Builder Kit Nodevember Instructions: getting-started/losant-iot-dev-kits/builder-kit-nodevember.md
        - Builder Kit Feather Instructions: getting-started/losant-iot-dev-kits/builder-kit-feather.md
        - Builder Kit Particle Instructions: getting-started/losant-iot-dev-kits/builder-kit-particle.md
        - Builder Kit Salesforce Instructions: getting-started/losant-iot-dev-kits/builder-kit-salesforce.md
        - Moisture Sensor Kit Instructions: getting-started/losant-iot-dev-kits/moisture-sensor-kit.md
        - Door Sensor Kit Instructions: getting-started/losant-iot-dev-kits/door-sensor-kit.md
        - LCD Kit Instructions: getting-started/losant-iot-dev-kits/lcd-kit.md
    - Boards:
        - Getting Started with Intel Edison: getting-started/boards/getting-started-with-intel-edison.md
        - Getting Started with Raspberry PI: getting-started/boards/getting-started-with-raspberry-pi.md
        - Getting Started with Arduino: getting-started/boards/getting-started-with-arduino-wifi-101.md
    - Tutorials And Projects: getting-started/tutorials.md
- Security:
    - Overview: security.md
- User Accounts:
    - Overview: user-accounts/overview.md
    - Sandbox: user-accounts/sandbox.md
- Organizations:
    - Overview: organizations/overview.md
    - Resource Limits: organizations/resource-limits.md
    - Transferring Resources: organizations/transferring-resources.md
- Applications:
    - Overview: applications/overview.md
    - Access Keys: applications/access-keys.md
    - Data Explorer: applications/data-explorer.md
    - Webhooks: applications/webhooks.md
- Events:
    - Overview: events/overview.md
- Devices:
    - Device Overview: devices/overview.md
    - Device State: devices/state.md
    - Device Commands: devices/commands.md
    - Device Queries: devices/device-queries.md
    - Gateways and Peripherals : devices/gateways-peripherals.md
    - Device Recipes: devices/device-recipes.md
- Dashboards:
    - Overview: dashboards/overview.md
    - Time Series Graph: dashboards/time-series-graph.md
    - GPS Heatmap: dashboards/gps-heatmap.md
    - GPS History: dashboards/gps-history.md
    - Gauge: dashboards/gauge.md
    - Pie Chart: dashboards/pie-chart.md
    - Bar Chart: dashboards/bar-chart.md
    - Input Controls: dashboards/input-controls.md
    - Data Table: dashboards/data-table.md
    - Device Connection Log: dashboards/device-connection-log.md
    - Event List: dashboards/event-list.md
    - Indicator: dashboards/indicator.md
    - Open Event Indicator: dashboards/open-event-indicator.md
    - External Website: dashboards/external-website.md
    - Device List: dashboards/device-list.md
    - Workflow List: dashboards/workflow-list.md
    - Application List: dashboards/application-list.md
    - Dashboard List: dashboards/dashboard-list.md
- Workflows:
    - Overview: workflows/overview.md
    - Accessing Payload Data: workflows/accessing-payload-data.md
    - Triggers:
        - Device: workflows/triggers/device.md
        - On Connect: workflows/triggers/on-connect.md
        - On Disconnect: workflows/triggers/on-disconnect.md
        - Event: workflows/triggers/event.md
        - MQTT: workflows/triggers/mqtt.md
        - Timer: workflows/triggers/timer.md
        - Virtual Button: workflows/triggers/virtual-button.md
        - Webhook: workflows/triggers/webhook.md
    - Logic:
        - Conditional: workflows/logic/conditional.md
        - Delay: workflows/logic/delay.md
        - Function: workflows/logic/function.md
        - Geofence: workflows/logic/geofence.md
        - JSON Encode: workflows/logic/json-encode.md
        - JSON Decode: workflows/logic/json-decode.md
        - Latch: workflows/logic/latch.md
        - Math: workflows/logic/math.md
        - Mutate: workflows/logic/mutate.md
        - On Change: workflows/logic/on-change.md
        - Random Number: workflows/logic/random-number.md
        - Throttle: workflows/logic/throttle.md
        - Time Range: workflows/logic/time-range.md
        - Validate Payload: workflows/logic/validate-payload.md
    - Data:
        - AWS Lambda: workflows/data/aws-lambda.md
        - Gauge Query: workflows/data/gauge-query.md
        - Get Value: workflows/data/get-value.md
        - HTTP: workflows/data/http.md
        - Losant API: workflows/data/losant-api.md
        - MongoDB: workflows/data/mongo.md
        - Redis: workflows/data/redis.md
        - Salesforce Cases: workflows/data/salesforce-cases.md
        - Store Value: workflows/data/store-value.md
    - Outputs:
        - Debug: workflows/outputs/debug.md
        - Device Command: workflows/outputs/device-command.md
        - Device State: workflows/outputs/device-state.md
        - Record Event: workflows/outputs/record-event.md
        - HTTP: workflows/outputs/http.md
        - Modify Event: workflows/outputs/modify-event.md
        - MQTT: workflows/outputs/mqtt.md
        - SendGrid: workflows/outputs/sendgrid.md
        - Slack: workflows/outputs/slack.md
        - Email: workflows/outputs/email.md
        - SMS: workflows/outputs/sms.md
        - Tweet: workflows/outputs/tweet.md
        - Twilio: workflows/outputs/twilio.md
        - Webhook Reply: workflows/outputs/webhook-reply.md
        - Workflow Trigger: workflows/outputs/workflow-trigger.md
- Losant Go:
    - Overview: losant-go/overview.md
- MQTT:
    - Overview: mqtt/overview.md
    - Arduino: mqtt/arduino.md
    - JavaScript: mqtt/javascript.md
    - Python: mqtt/python.md
    - Ruby: mqtt/ruby.md
- REST API:
    - Overview: rest-api/overview.md
    - Access Token: rest-api/access-token.md
    - Access Tokens: rest-api/access-tokens.md
    - Application Key: rest-api/application-key.md
    - Application Keys: rest-api/application-keys.md
    - Application: rest-api/application.md
    - Applications: rest-api/applications.md
    - Auth: rest-api/auth.md
    - Dashboard: rest-api/dashboard.md
    - Dashboards: rest-api/dashboards.md
    - Data: rest-api/data.md
    - Device Recipe: rest-api/device-recipe.md
    - Device Recipes: rest-api/device-recipes.md
    - Device: rest-api/device.md
    - Devices: rest-api/devices.md
    - Event: rest-api/event.md
    - Events: rest-api/events.md
    - Me: rest-api/me.md
    - Organization: rest-api/org.md
    - Organizations: rest-api/orgs.md
    - Webhook: rest-api/webhook.md
    - Webhooks: rest-api/webhooks.md
    - Workflow: rest-api/flow.md
    - Workflows: rest-api/flows.md
    - Schemas: rest-api/schemas.md
- Limits:
    - Overview: limits/overview.md
theme_dir: 'losant'
extra:
  site_title: 'Losant Documentation'
  hidden: ['Builder Kit Feather Instructions', 'Access Token', 'Access Tokens', 'Builder Kit Nodevember Instructions']
